Series d'exercice : Pandas

In [110]:
import numpy as np
import pandas as pd

In [109]:
ventes = pd.DataFrame({
"Commande_ID": ["C001","C002","C003","C004","C004","C005","C006","C007","C008","C009","C010","C011"],
"Client_ID": [1,2,1,3,3,4,5,2,6,7,8,4],
"Ville": [" casa ","RABAT","Casa","Marrakech","Marrakech","rabat","CASA"," fes","FES","Casa","Rabat",None],
"Produit":
["PC","Telephone","Ecran","PC","PC","Telephone","Ecran","PC","Telephone","Ecran","PC","Telephone"],
"Montant": [8000,4500,np.nan,7000,7000,5200,3000,9100,4800,2500,15000,5300],
"Quantite": [1,2,2,1,1,3,2,1,2,3,1,2],
"Date_Commande": ["01/09/2026","03/09/2026","05/09/2026","07/09/2026","07/09/2026","10/09/2026",
"12/09/2026","14/09/2026","16/09/2026","18/09/2026","20/09/2026","22/09/2026"]
})
clients = pd.DataFrame({
"Client_ID": [1,2,3,4,6,7,9],
"Nom": ["Ali","Sara","Omar","Lina","Nadia","Youssef","Imane"],
"Segment":
["Particulier","Entreprise","Particulier","Entreprise","Particulier","Entreprise","Particulier"]
})
septembre = pd.DataFrame({
"Commande_ID": ["S01","S02","S03"],
"Ville": ["Casa","Rabat","Fes"],
"Montant": [3000,5000,4200]
})
octobre = pd.DataFrame({
"Commande_ID": ["O01","O02","O03"],
"Ville": ["Casa","Marrakech","Rabat"],
"Montant": [6100,3800,7200]
})
infos_clients = pd.DataFrame({
"Anciennete": [2,5,1,8,3,4,6],
"Actif": [True,True,False,True,True,True,False]
}, index=[1,2,3,4,6,7,9])

#1
ventes.head()
ventes.tail(3)
#2
""" ventes.ndim
ventes.info()
ventes.dtypes """
#3
ventes.loc[:,["Commande_ID","Ville","Montant"]]
#4
ventes.iloc[2:7,0:3]
#5
ventes[ventes["Montant"] >= 5000]
#6
ventes["Ville"] = ventes["Ville"].str.strip().str.title()
ventes[(ventes["Ville"].isin(["Casa","Rabat"])) & (ventes["Quantite"] >1)]
#7
ventes[ventes["Montant"].between(4000,8000)]
#8
ventes.loc[ventes["Produit"].isin(["PC","Ecran"]),["Produit","Ville","Montant"]]

   Produit      Ville  Montant
0       PC       Casa   8000.0
2    Ecran       Casa      NaN
3       PC  Marrakech   7000.0
4       PC  Marrakech   7000.0
6    Ecran       Casa   3000.0
7       PC        Fes   9100.0
9    Ecran       Casa   2500.0
10      PC      Rabat  15000.0

B- Colonnes, types et transformation simple

In [118]:
#9
ventes["CA"] = ventes["Montant"] * ventes["Quantite"]
#10
ventes["Montant_TTC"] = ventes["Montant"] * 1.20
#11
ventes = ventes.rename(columns = {"Quantite":"Qte"})
#12
ventes["Client_ID"] = ventes["Client_ID"].astype(str)
ventes.dtypes
#13
ventes = ventes.drop(columns=["Montant_TTC"])
#14
ventes_test = ventes.copy()
ventes_test  = ventes_test.rename(columns = {"Qte" : "Quantite"})

C- Valeurs manquantes

In [ ]:
#15
ventes.isna().sum()
ventes.isna().sum().sum()
#16
ventes.isna().any(axis=1)
#17
ventes["Montant"] = ventes["Montant"].fillna(ventes["Montant"].median())
# median est plus precise quand on a une valeur Aux antipodes  de les autres , 15000 par exemple
#18
ventes["Ville"] = ventes["Ville"].fillna(
    ventes["Ville"].mode()[0])
#19
ventes_copie = ventes.copy()
ventes_copie = ventes_copie.dropna(subset = ["Montant"])
#20
""" Je peux supprimer une ligne si elle contient une information indispensable 
manquante et si perdre cette ligne ne réduit pas trop mon dataset.
Je préfère remplacer la valeur lorsque je souhaite conserver la ligne et qu’il existe 
une valeur de remplacement raisonnable, par exemple la médiane pour une variable numérique 
ou le mode pour une variable catégorielle.
"""

D- Doublons et nettoyage de texte

In [ ]:
#21
ventes.duplicated().sum()
#22
ventes[ventes.duplicated(keep=False)]
#23
ventes = ventes.drop_duplicates()
#24
ventes["Ville"].str.strip().str.title()
#25
ventes.groupby("Ville")["Commande_ID"].count()
#26
ventes[ventes.duplicated(subset=["Commande_ID"],
    keep=False)]

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
dtype: bool

E- Dates

In [ ]:
#27
ventes["Date_Commande"] = pd.to_datetime(ventes["Date_Commande"],
    format = "%d/%m/%Y")
#28
ventes["Annee"] = ventes["Date_Commande"].dt.year
ventes["Mois"] = ventes["Date_Commande"].dt.month
ventes["Jour"] = ventes["Date_Commande"].dt.day
#29
ventes[ventes["Date_Commande"] >= "2026-09-10"]
#30
ventes["Date_Commande"].min()
ventes["Date_Commande"].max()
#31
ventes["Jours_Depuis_Premiere"] = (
    ventes["Date_Commande"]
    - ventes["Date_Commande"].iloc[0]
).dt.days

,Commande_ID,Client_ID,Ville,Produit,Montant,Quantite,Date_Commande,Annee,Mois,Jour,separante
0,C001,1,Casa,PC,8000.0,1,2026-09-01,2026,9,1,0 days
1,C002,2,Rabat,Telephone,4500.0,2,2026-09-03,2026,9,3,2 days
2,C003,1,Casa,Ecran,NaN,2,2026-09-05,2026,9,5,4 days
3,C004,3,Marrakech,PC,7000.0,1,2026-09-07,2026,9,7,6 days
4,C004,3,Marrakech,PC,7000.0,1,2026-09-07,2026,9,7,6 days
5,C005,4,Rabat,Telephone,5200.0,3,2026-09-10,2026,9,10,9 days
6,C006,5,Casa,Ecran,3000.0,2,2026-09-12,2026,9,12,11 days
7,C007,2,Fes,PC,9100.0,1,2026-09-14,2026,9,14,13 days
8,C008,6,Fes,Telephone,4800.0,2,2026-09-16,2026,9,16,15 days
9,C009,7,Casa,Ecran,2500.0,3,2026-09-18,2026,9,18,17 days
10,C010,8,Rabat,PC,15000.0,1,2026-09-20,2026,9,20,19 days
11,C011,4,NaN,Telephone,5300.0,2,2026-09-22,2026,9,22,21 days

F- GroupBy et agrégations

In [130]:
#32
ventes.groupby("Ville")["Montant"].sum()
#33
ventes.groupby("Produit")["Montant"].mean()
#34
ventes.groupby("Ville")["Montant"].agg(["min","max","mean"])
#35
ventes.groupby(["Ville","Produit"])["CA"].sum()
#36
rapport = ventes.groupby("Ville").agg({"CA":["sum"],"Montant":["mean"],"Commande_ID":["count"]})
#37
ventes.groupby("Produit").agg({"Qte":["sum"],"CA":["sum"],"Montant":["mean"]})
#38
rapport["CA"]["sum"].idxmax()

'Rabat'